# These are supported funding model platforms

github: swalabtech
buy_me_a_coffee: journiv
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
thanks_dev: # Replace with a single thanks.dev username
custom: https://buy.stripe.com/4gM9AVeGk3lE6PbfYRffy00
ko_fi: journiv
