/** Environment resolution for the E2E suite.
 *
 *  Every address the suite talks to is resolved here so the backend's lifecycle
 *  can move (developer-managed today, Docker Compose in CI tomorrow) without a
 *  single spec changing. Nothing else in `e2e/` reads `process.env` directly.
 */

/** Where the app under test is served. Playwright's `webServer` starts Vite on
 *  this port; 5199 is the project's existing convention
 * (`scripts/capture-design-reference.mjs`). */
export const APP_PORT = Number(process.env.JOURNIV_E2E_PORT ?? 5199);

export const BASE_URL =
  process.env.JOURNIV_E2E_BASE_URL ?? `http://127.0.0.1:${APP_PORT}`;

/** The backend origin. Fixtures call it directly rather than through Vite's
 *  `/api` proxy: one less moving part between a failed request and its cause. */
export const API_URL =
  process.env.JOURNIV_E2E_API_URL ?? "http://127.0.0.1:8000";

export const API_V1 = `${API_URL}/api/v1`;

/** Set when the app is already being served by something else (a CI job serving
 *  a production build, a dev server you want to keep). */
export const SKIP_WEB_SERVER = Boolean(process.env.JOURNIV_E2E_SKIP_WEBSERVER);

export const IS_CI = Boolean(process.env.CI);

/** Unique per `playwright test` invocation. Stamped into worker account emails
 *  so two concurrent runs against one backend cannot collide. `global-setup.ts`
 *  generates it; workers read it back out of the environment. */
export function runId(): string {
  const id = process.env.JOURNIV_E2E_RUN_ID;
  if (!id)
    throw new Error(
      "JOURNIV_E2E_RUN_ID is not set. It is generated by e2e/global-setup.ts — " +
        "run specs through `npm run test:e2e`, not by importing fixtures directly.",
    );
  return id;
}

/** The account a worker registers and, at teardown, deletes.
 *
 *  The domain is `example.com` rather than something like `journiv.test`
 *  because the backend validates with `email-validator`, which refuses
 *  special-use and reserved TLDs — `.test` fails with a 422. The backend's own
 *  pytest fixtures use `example.com` for the same reason.
 *
 *  The `e2e-` local-part prefix is the documented handle for finding accounts
 *  left behind by an interrupted run.
 */
export function workerEmail(workerIndex: number): string {
  return `e2e-${runId()}-w${workerIndex}@example.com`;
}

/** Backend policy: >= 8 characters, at least one letter and one digit
 *  (`app/schemas/user.py`). Generated per run — never a committed credential. */
export function workerPassword(workerIndex: number): string {
  return `E2e-${runId()}-w${workerIndex}-Aa1`;
}
